services:
  broker:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ADMIN_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ADMIN_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  grafana:
    volumes:
      - ./observability/grafana/provisioning/dashboards/02-MESSAGING/rabbitmq-broker.json:/etc/grafana/provisioning/dashboards/02-MESSAGING/rabbitmq-broker.json
volumes:
  rabbitmq_data:
    driver: local
