services:
  data-injector:
    image: scratch
    networks:
      - pathfinder_network_dev
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  timeseries-writer:
    image: scratch
    networks:
      - pathfinder_network_dev
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
