services:
  mqtt-injector:
    image: ghcr.io/redpanda-data/connect
    container_name: mqtt-injector
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/injectors.yaml:/connect.yaml
    networks:
      - pathfinder_network_dev
    environment:
      MQTT_PUBLISH_URL: "mqtt-broker:1883"
      MQTT_PUBLISH_TOPIC: processed/data
      MQTT_PUBLISH_QOS: 1
      MQTT_SUBSCRIBE_URL: "mqtt-broker:1883"
      MQTT_SUBSCRIBE_TOPIC: "home/#"
      MQTT_SUBSCRIBE_QOS: 1
      RABBITMQ_PUBLISH_URL: "amqp://${RABBITMQ_ADMIN_USER}:${RABBITMQ_ADMIN_PASSWORD}@broker:5672"
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  timescale-writer:
    image: ghcr.io/redpanda-data/connect
    container_name: timescale-writer
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/timescale-writer.yaml:/connect.yaml
      - ../../benthos/init_metrics_table.sql:/init_metrics_table.sql
    networks:
      - pathfinder_network_dev
    environment:
      RABBITMQ_SUBSCRIBE_URL: "amqp://${RABBITMQ_ADMIN_USER}:${RABBITMQ_ADMIN_PASSWORD}@broker:5672"
      RABBITMQ_SUBSCRIBE_QUEUE: timescale-writer
      TIMESCALE_USER: tsdbadmin
      TIMESCALE_ADMIN_PASSWORD: ${TIMESCALE_ADMIN_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  influx-writer:
    image: ghcr.io/redpanda-data/connect
    container_name: influx-writer
    command: ["-w", "-c", "/connect.yaml"]
    volumes:
      - ../../benthos/influx-writer.yaml:/connect.yaml
    networks:
      - pathfinder_network_dev
    environment:
      RABBITMQ_SUBSCRIBE_URL: "amqp://${RABBITMQ_ADMIN_USER}:${RABBITMQ_ADMIN_PASSWORD}@broker:5672"
      RABBITMQ_SUBSCRIBE_QUEUE: influx-writer
      INFLUXDB_WRITE_URL: "influxdb:8181"
      INFLUXDB_WRITE_TOKEN: ${INFLUXDB_WRITE_TOKEN}
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
