services:
  mqtt-broker:
    image: scratch
    restart: unless-stopped
    networks:
      - pathfinder_network_dev

  broker:
    image: scratch
    restart: unless-stopped
    networks:
      - pathfinder_network_dev
