services:
  hivemq:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"
      - "8083:8080"
    container_name: hivemq-edge
    restart: unless-stopped
    networks:
      - pathfinder_network_dev

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_ADMIN_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ADMIN_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - pathfinder_network_dev

volumes:
  rabbitmq_data:
    driver: local
