services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      - TIMESCALEDB_TELEMETRY=on # Disable telemetry
      - TS_TUNE_MEMORY=4GB # Set available memory for tuning
      - TS_TUNE_NUM_CPUS=4 # Set number of CPUs for tuning
      - TS_TUNE_MAX_BG_WORKERS=16 # Set maximum number of background workers
      - TS_TUNE_MAX_CONNS=200 # Set maximum number of connections
      - NO_TS_TUNE=false # Run timescaledb-tune (set to true to disable tuning)
    volumes:
      - timescaledb-data:/var/lib/postgresql/data # Persist data to a named volume
    networks:
      - pathfinder_network_dev

  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    user: "root:root"
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      # - --wal-replay-fail-on-error
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb-data:/var/lib/influxdb3/data
      - influxdb-plugins:/var/lib/influxdb3/plugins
    networks:
      - pathfinder_network_dev

  influxdb-explorer:
    image: influxdata/influxdb3-ui:1.2.0
    container_name: influxdb-explorer
    command: ["--mode=admin"]
    ports:
      - "8090:80"
    volumes:
      - ./influxdb-explorer:/db
      # - ./config:/app-root/config:ro
      # - ./ssl:/etc/nginx/ssl:ro
    configs:
      - source: influxdb-explorer
        target: /app-root/config/config.json
    environment:
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
    restart: unless-stopped
    networks:
      - pathfinder_network_dev

configs:
  influxdb-explorer:
    content: |
      {
        "DEFAULT_INFLUX_SERVER": "http://influxdb:8181",
        "DEFAULT_INFLUX_DATABASE": "data",
        "DEFAULT_API_TOKEN": "${INFLUXDB_ADMIN_TOKEN}",
        "DEFAULT_SERVER_NAME": "pathfinder-demo"
      }

volumes:
  timescaledb-data:
    driver: local
  influxdb-data:
    driver: local
  influxdb-plugins:
    driver: local
  influxdb-explorer:
    driver: local
