services:
  timeseriesdb:
    image: influxdb:3-core
    container_name: influxdb
    user: "root:root"
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      # - --wal-replay-fail-on-error
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - influxdb-data:/var/lib/influxdb3/data
      - influxdb-plugins:/var/lib/influxdb3/plugins
    networks:
      - pathfinder_network_dev

  influxdb-explorer:
    image: influxdata/influxdb3-ui:1.2.0
    container_name: influxdb-explorer
    command: ["--mode=admin"]
    ports:
      - "8090:80"
    volumes:
      - ./influxdb-explorer:/db
      # - ./config:/app-root/config:ro
      # - ./ssl:/etc/nginx/ssl:ro
    configs:
      - source: influxdb-explorer
        target: /app-root/config/config.json
    environment:
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
    restart: unless-stopped
    networks:
      - pathfinder_network_dev

  grafana:
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=newInfluxDSConfigPageDesign
      - INFLUXDB_URL=http://influxdb:8181
      - INFLUXDB_TOKEN=${INFLUXDB_WRITE_TOKEN}
      - INFLUXDB_DBNAME=raw
    volumes:
      - ./observability/grafana/provisioning/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml

configs:
  influxdb-explorer:
    content: |
      {
        "DEFAULT_INFLUX_SERVER": "http://influxdb:8181",
        "DEFAULT_INFLUX_DATABASE": "data",
        "DEFAULT_API_TOKEN": "${INFLUXDB_ADMIN_TOKEN}",
        "DEFAULT_SERVER_NAME": "pathfinder-demo"
      }

volumes:
  influxdb-data:
    driver: local
  influxdb-plugins:
    driver: local
  influxdb-explorer:
    driver: local
